//! Stable per-host machine identifier.
//!
//! Returns a SHA-256 hash (lowercase hex) of a per-OS-stable identifier so
//! the platform can refuse a token that's been copied to a second machine.
//!
//! ## Sources
//!
//! - **Linux**: `/etc/machine-id` (systemd), falling back to
//!   `/var/lib/dbus/machine-id`. Both are 32-hex strings written once at
//!   first boot and stable across reboots; only regenerated by
//!   `systemd-machine-id-setup` (e.g. cloned VM images).
//! - **Windows**: `HKLM\SOFTWARE\Microsoft\Cryptography\MachineGuid`. Set at
//!   OS install, GUID, readable without admin. We shell out to `reg.exe`
//!   instead of taking a `windows-sys` registry feature dep — the call runs
//!   exactly once at agent startup.
//!
//! ## Privacy
//!
//! We never send the raw value. We send `sha256("connlog-machine-id|" + raw)`
//! so the platform can't correlate this hash with anything else (e.g. the
//! same `/etc/machine-id` used by another vendor's agent on the same box).
//!
//! ## Failure mode
//!
//! If we can't read the source for any reason, returns `None`. The platform
//! treats a missing `X-Machine-Id` header as "agent is too old to send one"
//! and falls back to the existing hostname binding — a future v1.3 can make
//! the header mandatory once the fleet has rolled over.
//!
//! Computed once at agent startup and cached for the process lifetime.

use ring::digest;

const HASH_PREFIX: &str = "connlog-machine-id|";

/// Read + hash the machine identifier. Returns `None` if no source is available.
pub fn machine_id() -> Option<String> {
    let raw = read_raw_machine_id()?;
    let trimmed = raw.trim();
    if trimmed.is_empty() {
        return None;
    }
    let mut input = String::with_capacity(HASH_PREFIX.len() + trimmed.len());
    input.push_str(HASH_PREFIX);
    input.push_str(trimmed);
    let digest = digest::digest(&digest::SHA256, input.as_bytes());
    Some(hex_encode(digest.as_ref()))
}

#[cfg(target_os = "linux")]
fn read_raw_machine_id() -> Option<String> {
    // /etc/machine-id is the systemd-managed source of truth. The dbus path
    // exists on older / non-systemd systems and as a symlink on most modern
    // distros, but we read it explicitly as a fallback.
    std::fs::read_to_string("/etc/machine-id")
        .ok()
        .or_else(|| std::fs::read_to_string("/var/lib/dbus/machine-id").ok())
}

#[cfg(target_os = "windows")]
fn read_raw_machine_id() -> Option<String> {
    use std::process::Command;
    // `reg query <key> /v MachineGuid` prints lines like:
    //     MachineGuid    REG_SZ    {12345678-1234-1234-1234-1234567890ab}
    // We grab the trailing token from the line that contains "MachineGuid".
    let output = Command::new("reg")
        .args([
            "query",
            r"HKLM\SOFTWARE\Microsoft\Cryptography",
            "/v",
            "MachineGuid",
        ])
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let stdout = String::from_utf8_lossy(&output.stdout);
    for line in stdout.lines() {
        let line = line.trim();
        if !line.contains("MachineGuid") {
            continue;
        }
        if let Some(value) = line.split_whitespace().last() {
            // Strip surrounding braces if present.
            let v = value.trim_matches(|c| c == '{' || c == '}');
            if !v.is_empty() {
                return Some(v.to_string());
            }
        }
    }
    None
}

#[cfg(target_os = "macos")]
fn read_raw_machine_id() -> Option<String> {
    use std::process::Command;
    // `ioreg -rd1 -c IOPlatformExpertDevice` includes a line:
    //     "IOPlatformUUID" = "12345678-1234-1234-1234-1234567890AB"
    let output = Command::new("ioreg")
        .args(["-rd1", "-c", "IOPlatformExpertDevice"])
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let stdout = String::from_utf8_lossy(&output.stdout);
    for line in stdout.lines() {
        if let Some(rest) = line.split("\"IOPlatformUUID\"").nth(1) {
            if let Some(value) = rest.split('"').nth(1) {
                if !value.is_empty() {
                    return Some(value.to_string());
                }
            }
        }
    }
    None
}

#[cfg(not(any(target_os = "linux", target_os = "windows", target_os = "macos")))]
fn read_raw_machine_id() -> Option<String> {
    None
}

fn hex_encode(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        out.push(nibble(b >> 4));
        out.push(nibble(b & 0x0f));
    }
    out
}

fn nibble(n: u8) -> char {
    match n {
        0..=9 => (b'0' + n) as char,
        _ => (b'a' + n - 10) as char,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hash_is_64_hex_chars_when_available() {
        // On supported OSes (linux/windows/macos) this should produce a hash;
        // on the test host (Linux), `/etc/machine-id` virtually always exists.
        if let Some(id) = machine_id() {
            assert_eq!(id.len(), 64, "sha256 hex must be 64 chars");
            assert!(
                id.chars()
                    .all(|c| c.is_ascii_hexdigit() && !c.is_uppercase()),
                "must be lowercase hex"
            );
        }
    }

    #[test]
    fn hash_is_stable() {
        let a = machine_id();
        let b = machine_id();
        assert_eq!(a, b, "machine_id must be deterministic across calls");
    }

    #[test]
    fn hash_is_prefixed_so_other_vendors_get_a_different_hash() {
        // Verify our prefix actually changes the digest vs raw. We do this
        // by hashing a known value with + without the prefix and checking
        // they differ — protects against the prefix being deleted.
        let raw = "test-machine-id";
        let with_prefix = digest::digest(
            &digest::SHA256,
            format!("{}{}", HASH_PREFIX, raw).as_bytes(),
        );
        let without_prefix = digest::digest(&digest::SHA256, raw.as_bytes());
        assert_ne!(with_prefix.as_ref(), without_prefix.as_ref());
    }
}
