//! Stable per-host machine identifier.
//!
//! Returns a SHA-256 hash (lowercase hex) of a per-OS-stable identifier so
//! the platform can notice a token that has been copied to a second machine
//! (a cloned image, a config pasted onto the wrong host). It is not a theft
//! control: `/etc/machine-id` is world-readable, so anyone who can read the
//! token can compute this header too.
//!
//! ## Sources
//!
//! - **Linux**: `/etc/machine-id` (systemd), falling back to
//!   `/var/lib/dbus/machine-id`. Both are 32-hex strings written once at
//!   first boot and stable across reboots; only regenerated by
//!   `systemd-machine-id-setup` (e.g. cloned VM images).
//!
//! ## Privacy
//!
//! We never send the raw value. We send `sha256("connlog-machine-id|" + raw)`
//! so the platform can't correlate this hash with anything else.
//!
//! ## Failure mode
//!
//! If we can't read the source for any reason, returns `None`. The platform
//! treats a missing `X-Machine-Id` header as "agent is too old to send one"
//! and falls back to the existing hostname binding.
//!
//! Computed once at agent startup and cached for the process lifetime.

use ring::digest;

const HASH_PREFIX: &str = "connlog-machine-id|";

/// Read + hash the machine identifier. Returns `None` if no source is available.
pub fn machine_id() -> Option<String> {
    let raw = read_raw_machine_id()?;
    let trimmed = raw.trim();
    if trimmed.is_empty() {
        return None;
    }
    let mut input = String::with_capacity(HASH_PREFIX.len() + trimmed.len());
    input.push_str(HASH_PREFIX);
    input.push_str(trimmed);
    let digest = digest::digest(&digest::SHA256, input.as_bytes());
    Some(hex_encode(digest.as_ref()))
}

#[cfg(target_os = "linux")]
fn read_raw_machine_id() -> Option<String> {
    std::fs::read_to_string("/etc/machine-id")
        .ok()
        .or_else(|| std::fs::read_to_string("/var/lib/dbus/machine-id").ok())
}

#[cfg(not(target_os = "linux"))]
fn read_raw_machine_id() -> Option<String> {
    None
}

fn hex_encode(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        out.push(nibble(b >> 4));
        out.push(nibble(b & 0x0f));
    }
    out
}

fn nibble(n: u8) -> char {
    match n {
        0..=9 => (b'0' + n) as char,
        _ => (b'a' + n - 10) as char,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hash_is_64_hex_chars_when_available() {
        if let Some(id) = machine_id() {
            assert_eq!(id.len(), 64, "sha256 hex must be 64 chars");
            assert!(
                id.chars()
                    .all(|c| c.is_ascii_hexdigit() && !c.is_uppercase()),
                "must be lowercase hex"
            );
        }
    }

    #[test]
    fn hash_is_stable() {
        let a = machine_id();
        let b = machine_id();
        assert_eq!(a, b, "machine_id must be deterministic across calls");
    }

    #[test]
    fn hash_is_prefixed_so_other_vendors_get_a_different_hash() {
        let raw = "test-machine-id";
        let with_prefix = digest::digest(
            &digest::SHA256,
            format!("{}{}", HASH_PREFIX, raw).as_bytes(),
        );
        let without_prefix = digest::digest(&digest::SHA256, raw.as_bytes());
        assert_ne!(with_prefix.as_ref(), without_prefix.as_ref());
    }
}
